apiVersion: v1
kind: Service
metadata:
  name: game-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: clashbots
spec:
  type: ClusterIP
  ports:
    - name: game-service
      port: 9006
  selector:
    app: clashbots